### PR TITLE
feat: API middleware

### PR DESCRIPTION
**Pull request by rtritto**
Try to implement point 3. in https://github.com/magne4000/universal-middleware/discussions/86#discussioncomment-11574261

### CODE REVIEW

**Comment by brillout** [comment]
As said [here](https://github.com/magne4000/universal-middleware/discussions/86#discussioncomment-11532167), this is out of scope for now. Thus closing.

**Comment by brillout** [comment]
If you want to contribute (which is very much welcome on our side), it can only work if you trust and follow our leadership.

**Comment by rtritto** [comment]
> As said [here](https://github.com/magne4000/universal-middleware/discussions/86#discussioncomment-11532167), this is out of scope for now. Thus closing.

But how can it be achieved?

The use case is explained here: https://github.com/magne4000/universal-middleware/discussions/86#discussioncomment-11574261

There is a way in vike or vike-node (or new feature) to export the ViteDevServer instance to use in [universal-autoloader](https://github.com/node-ecosystem/universal-autoloader) (it already have the `viteDevServer.ssrLoadModule` implementation)?

Maybe an example can be added in https://vike.dev/api-routes to help anywone with same use case.

**Comment by brillout** [comment]
Response [here](https://github.com/vikejs/vike-node/issues/35#issuecomment-2552280863).

**Pull request closed without merging**
