### PR TITLE
refactor: use node protocol on imports

### PR DESCRIPTION
**Pull request by rtritto**

### CODE REVIEW

**Comment by brillout** [comment]
Curious: what's the rationale for doing this?

**Comment by rtritto** [comment]
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-node-protocol.md

**Comment by brillout** [comment]
So it's only about style, right?

The style should be determined by the maintainer, not by contributors. Thus closing. (Personally, I'm in favor of this rule, but it isn't my role to take that decision. It should be @nitedani that takes the decision in that regard.)

It's best when contributors focus on bugs of feature requests, while leaving stylistic decisions to the maintainers.

**Comment by rtritto** [comment]
Is a best practice to get more readability and a standard used by the Node.js (documentation) and the community.
Have no sense to reject a simple and completed PR because focus is on other side. Projects should receive all the help they can get especially since they are still under the (early) development stage.

**Comment by brillout** [comment]
I do personally agree it's a slightly better. But, again, it's best when it's the lead maintainer that takes these kind of decisions which are more often than not subjective. For example, your PR introduces a merge conflict to Joël's PR. (That's actually why I would reject such PR on Vike core: I wouldn't want a PR to introduce a merge conflict to other PRs for merely a stylistic change.)

It's also best if contributors trust maintainers and let maintainers lead. So I'll ask you to be a little bit careful about that. Thank you.

**Comment by rtritto** [comment]
@brillout using the no-standard protocol and mixin (no-standard + standard), some bundle has dupe imports.

See `import path6 from 'path'` and `import path3 from 'node:path'`:
```ts
// vike-node@0.3.0/dist/plugin/index.js
...
import path6 from 'path';
import { promisify } from 'util';
import esbuild from 'esbuild';
import fs2 from 'fs/promises';
import { prerender } from 'vike/api';
import { readFileSync } from 'fs';
import { createRequire as createRequire$1, builtinModules } from 'node:module';
import path3 from 'node:path';
...
```

**Comment by brillout** [comment]
I don't think it makes any difference? It's best you reach out only if you have *evidence* that there is an issue, not if you only *speculate* there is one. As always: let's focus more on real stuff (bug fixes and new features).

That said, AFAIK vike-node doesn't have any pending refactor PRs, so we can revive this PR if you want (as a new separate PR). (It's actually something I want to do for `vike` as well as soon as I've resolved all pending PRs.)

**Comment by rtritto** [comment]
@brillout Deno needs node protocol to use bult-in modules of Deno:

> Deno supports most built-in Node.js modules natively - you can include them in your code using "node:" specifiers in your imports.

Source: https://docs.deno.com/examples/node_built_in

PS: let me know if I can help with this PR

**Comment by magne4000** [comment]
@rtritto on `main` branch all import have been rewritten with `node:` prefix.

**Pull request closed without merging**
